### ISSUE TITLE
Pets stuck climbing blocks (2.0+)

### ISSUE THREAD

**Issue by SpEeD11** [MiniaturePets/Issues#66]
Pets get stuck climbing single blocks on version 2.0+ (gif of issue: https://media.giphy.com/media/pqLYsrGKiv5GaqPFhX/giphy.gif)

Miniature Pets Dump: https://pastebin.com/iFX6DdrZ

**Comment by danielntech** [comment]
Hi, getting far enough should make them teleport automatically to you.

**Comment by SpEeD11** [comment]
it worked fine in previous versions before 2.0, could you check if its a simple fix like changing a Y value or something? Relying on teleports kind of defeats the purpose of having pets that follow you.

**Comment by danielntech** [comment]
I see, I have escalated that to our development team.

Sorry for the inconvenience.

**Comment by NacOJerk** [comment]
Should be fixed now :)

**Comment by SpEeD11** [comment]
just checked the latest version aswell and the version right after when this issue was closed, the problem still exists
